WebAppMVCGit/Models/Emp.cs
namespace WebAppMVCGit.Models
{
    public class Emp
    {
        public int EId { get; set; }
        public string EName { get; set; }
        public string EDesign {  get; set; }
        public DateTime EDOJ { get; set; }
    }
}

WebAppMVCGit/Models/ErrorViewModel.cs
namespace WebAppMVCGit.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppMVCGit/Controllers/EmpController.cs
using Microsoft.AspNetCore.Mvc;
using System.Numerics;
using WebAppMVCGit.Models;

namespace WebAppMVCGit.Controllers
{
    public class EmpController : Controller
    {
        List<Emp> _emps = new List<Emp>()
        {
            new Emp(){EId=1,EName="Sam Dicosta",EDesign="Developer",EDOJ=new DateTime(day:4,month:02,year:2020)},
               new Emp(){EId=1,EName="Sam Dicosta",EDesign="Developer",EDOJ=new DateTime(day:4,month:02,year:2020)},
                new Emp(){EId=1,EName="Sam Dicosta",EDesign="Developer",EDOJ=new DateTime(day:4,month:02,year:2020)},
                 new Emp(){EId=1,EName="Sam Dicosta",EDesign="Developer",EDOJ=new DateTime(day:4,month:02,year:2020)}

        };
        public IActionResult Index()
        {
            return View(_emps);
        }
    }
}

WebAppMVCGit/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppMVCGit.Models;

namespace WebAppMVCGit.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppMVCGit/Views/Emp/Index.cshtml
@model IEnumerable<WebAppMVCGit.Models.Emp>

@{
    ViewData["Title"] = "Index";
 
}
<partial name="PartialView" model="Model" />

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EDesign)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EDOJ)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDesign)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDOJ)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WebAppMVCGit/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAppMVCGit/Views/Shared/PartialView.cshtml
<h2 class="text-center">TREE Company Limited</h2>
<hr />
<img src="~/images/bg1.jpg" class="img-thumbnail rounded" height="200" width="200px" />
<img src="~/images/bg2.jpg" class="img-thumbnail rounded" height="200" width="200px" />

WebAppMVCGit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppMVCGit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppMVCGit.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppMVCGit</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Index">Emp</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebAppMVCGit - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>